---
- name: Create an Inventory and hosts on the AAP Host
  hosts: all
  gather_facts: false
  vars: 
    homelab_hosts:
      - xerxes.thenorvilles.com
      - caesar.thenorvilles.com
      - hannibal.thenorvilles.com
      - attila.thenorvilles.com

  tasks: 

    - name: Add an inventory to AAP
      ansible.controller.inventory:
        name: "The Rick James Inventory"
        description: "The Best Inventory of all Time!"
        organization: Default
        state: present

    - name: Add homelab hosts to the New Inventory
      ansible.controller.host:
        name: "{{ item }}"
        inventory: "The Rick James Inventory"
        state: present
      loop: "{{ homelab_hosts }}"