---
- name: Remove Inventory and hosts on the AAP Host
  hosts: all
  gather_facts: false
  vars: 
    homelab_hosts:
      - xerxes.thenorvilles.com
      - caesar.thenorvilles.com
      - hannibal.thenorvilles.com
      - attila.thenorvilles.com

  tasks: 

    - name: Remove homelab hosts
      ansible.controller.host:
        name: "{{ item }}"
        inventory: "The Rick James Inventory"
        state: absent
      loop: "{{ homelab_hosts }}"

    - name: Remove a Group
      ansible.controller.group:
        name: HomeLab
        inventory: "The Rick James Inventory"
        state: absent
        
    - name: Remove an inventory in AAP
      ansible.controller.inventory:
        name: "The Rick James Inventory"
        organization: Default
        state: absent

